import Head from 'next/head';

const MetaInfo: React.FC = () => {
  return (
    <Head>
      <title>Drive Score</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default MetaInfo;
